package loader

import (
	"cmp"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"slices"
	"strings"

	"github.com/home-operations/flate/pkg/manifest"
	"github.com/home-operations/flate/pkg/store"
)

// SelfProduceIndex maps a ConfigMap id (kind + resolved namespace +
// name) to the Flux Kustomization(s) whose OWN render subtree emits it.
//
// It exists for one job: let collectDeps tell a self-substitute apart
// from a cross-KS substituteFrom. A Kustomization that renders the very
// ConfigMap it lists in postBuild.substituteFrom (the bjw-s/onedr0p
// `cluster-apps` → `cluster-settings` pattern: a bare-dir spec.path whose
// subdir bases pull in a component defining the CM) must NOT hard-wait on
// that CM — no other reconcile can produce it, so depwait would deadlock
// the consumer against its own render. A CM produced by a DIFFERENT KS,
// or genuinely absent, is left out of this index so its dependency edge
// stays and still fails loudly.
//
// Built once per Bootstrap (in discovery.Run) and read-only afterwards.
type SelfProduceIndex struct {
	byID map[manifest.NamedResource][]manifest.NamedResource
	// emissionParentByFile: cross-tree base ks.yaml path → its single emitting
	// parent KS. See EmissionParentByFile.
	emissionParentByFile map[string]manifest.NamedResource
}

// ProducedBy returns the Kustomizations whose render subtree emits cm.
// Nil-safe: a nil index (no repoRoot, stripped-down tests) produces no
// matches, so collectDeps falls back to the always-add edge behavior.
func (i *SelfProduceIndex) ProducedBy(cm manifest.NamedResource) []manifest.NamedResource {
	if i == nil {
		return nil
	}
	return i.byID[cm]
}

// EmissionParentByFile returns the Flux Kustomization whose render subtree emits
// the ks.yaml at the given repo-relative path, when exactly one does — i.e. a
// cross-tree kustomize base (apps/base/app-X/ks.yaml pulled in via
// apps/test/app-X -> ../../base/app-X, applied by cluster-apps with postBuild
// substitution). discovery.Run gates such a base on that parent so it reconciles
// the parent's substituted emission, not the raw file. Keyed by FILE so it maps
// onto the loaded copy's store id regardless of namespace inheritance; nil-safe.
// See #777.
func (i *SelfProduceIndex) EmissionParentByFile(file string) (manifest.NamedResource, bool) {
	if i == nil {
		return manifest.NamedResource{}, false
	}
	p, ok := i.emissionParentByFile[file]
	return p, ok
}

// BuildSelfProduceIndex resolves, per Flux Kustomization with a spec.path,
// which ConfigMaps its own kustomize render emits and in which namespace —
// by walking the render graph the loader's discovery pass does not attribute
// to a producer: bare-dir base generation (each immediate subdir holding a
// kustomization file becomes a base, mirroring Flux's own generator),
// recursion through `resources:` (files + nested bases) and `components:`,
// and propagation of each layer's `namespace:` transformer. repoRoot anchors
// the on-disk reads; an empty repoRoot yields an empty (but usable) index.
//
// The same walk doubles as the discovery-time producer scan: when producers is
// non-nil, every in-repo ExternalSecret / SealedSecret it encounters is
// recorded as target-Secret → producer, with the same effective-namespace
// resolution applied to ConfigMaps. This seeds the producer index BEFORE any
// source fetch (sources reconcile early), so producer-backed auth Secrets can
// be skipped without --allow-missing-secrets. It rides this walk so it inherits
// the namespace-transform faithfulness and reads each file once. Producers
// generated by ResourceSets/kustomize generators, or whose name is rewritten by
// a namePrefix/nameSuffix, are not covered here — they fall back to the
// render-time listener (valuesFrom) or fail-loud/the flag (source auth).
func BuildSelfProduceIndex(s *store.Store, repoRoot string, producers *manifest.ProducerIndex, wipeSecrets bool, existence *ExistenceIndex) *SelfProduceIndex {
	idx := &SelfProduceIndex{
		byID:                 map[manifest.NamedResource][]manifest.NamedResource{},
		emissionParentByFile: map[string]manifest.NamedResource{},
	}
	if repoRoot == "" {
		return idx
	}
	b := &selfProduceBuilder{
		repoRoot:     repoRoot,
		dirs:         map[string]cachedDir{},
		idx:          idx,
		emittedFiles: map[string][]manifest.NamedResource{},
		producers:    producers,
		store:        s,
		wipeSecrets:  wipeSecrets,
	}
	// A KS sourced from a genuine external repo renders that repo's tree, not the
	// local checkout — walking its spec.path against repoRoot would record it as
	// producing local ConfigMaps/Secrets it doesn't own (and cascade its skip).
	// See loader.ExternalSourcedKSIDs.
	external := ExternalSourcedKSIDs(s, repoRoot, existence)
	for _, ks := range store.ListAs[*manifest.Kustomization](s, manifest.KindKustomization) {
		if ks.Path == "" {
			continue
		}
		if _, skip := external[ks.Named()]; skip {
			continue
		}
		b.walkRoot(ks)
	}
	// Keep only files reached through exactly one parent — a base shared by peer
	// overlays is ambiguous, so add no gate.
	for file, parents := range b.emittedFiles {
		if len(parents) == 1 {
			idx.emissionParentByFile[file] = parents[0]
		}
	}
	return idx
}

type cachedDir struct {
	d  kustomizeDirectives
	ok bool
}

type selfProduceBuilder struct {
	repoRoot string
	// dirs memoizes whole-file kustomization reads (namespace / resources /
	// components) keyed by repo-relative dir, so subtrees shared across the
	// KS list — every app group's substitutions component, say — are read
	// once. Discovery is serial, so no lock is needed.
	dirs map[string]cachedDir
	idx  *SelfProduceIndex
	// emittedFiles accumulates each cross-tree-emitted ks.yaml path → the
	// distinct parents reaching it; resolved to single-parent
	// emissionParentByFile edges after the walk.
	emittedFiles map[string][]manifest.NamedResource
	// producers, when non-nil, receives target-Secret → ExternalSecret /
	// SealedSecret edges discovered during the same walk. See
	// BuildSelfProduceIndex.
	producers *manifest.ProducerIndex
	// store receives a synthetic placeholder Secret for each producer whose
	// output keys are statically declared (see synthesizePlaceholderSecret).
	store *store.Store
	// wipeSecrets gates the placeholder synthesis — it is a wipe-mode behavior
	// (a stand-in for a secret flate can't read offline), matching the SOPS
	// ciphertext wipe; --no-wipe-secrets leaves the secret genuinely absent.
	wipeSecrets bool
}

// directives returns the (memoized) kustomization directives at the
// repo-relative dir; ok is false when no kustomization file is present.
func (b *selfProduceBuilder) directives(dir string) (kustomizeDirectives, bool) {
	if c, ok := b.dirs[dir]; ok {
		return c.d, c.ok
	}
	d, ok := readKustomizeDirectives(b.repoRoot, dir)
	b.dirs[dir] = cachedDir{d: d, ok: ok}
	return d, ok
}

// walkRoot enumerates the base(s) of a Flux Kustomization's spec.path and
// walks each. A spec.path that holds a kustomization file is itself the
// single base; a bare spec.path (no kustomization file — Flux's generator
// synthesizes one listing the subdirs) contributes each immediate subdir
// that holds a kustomization file. The root imposes no namespace of its
// own (Flux's generated kustomization sets only `resources:`); rootNS is
// the consumer-side fallback for a ConfigMap that no layer ever stamps.
func (b *selfProduceBuilder) walkRoot(ks *manifest.Kustomization) {
	id := ks.Named()
	rootNS := cmp.Or(ks.TargetNamespace, ks.Namespace)
	specDir := manifest.NormalizeClaimBase(ks.Path)
	visited := map[string]struct{}{}

	if _, ok := b.directives(specDir); ok {
		b.walkBase(specDir, "", rootNS, id, visited)
		return
	}
	entries, err := os.ReadDir(filepath.Join(b.repoRoot, specDir))
	if err != nil {
		return
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		sub := path.Join(specDir, e.Name())
		if _, ok := b.directives(sub); ok {
			b.walkBase(sub, "", rootNS, id, visited)
		}
	}
}

// walkBase walks one kustomize base (or component) at the repo-relative
// dir, recording the ConfigMaps it emits for ks. parentNS is the namespace
// inherited from the enclosing layer; baseNS applies the kustomize-faithful
// rule that the OUTER (ancestor) `namespace:` wins — once an ancestor set
// one it is locked, so an inner base's directive cannot override it.
func (b *selfProduceBuilder) walkBase(dir, parentNS, rootNS string, ks manifest.NamedResource, visited map[string]struct{}) {
	if dir == "" || strings.HasPrefix(dir, "..") {
		return // outside the repo root — never read
	}
	// Key the cycle guard by (dir, inherited namespace): a shared component
	// (e.g. ../../components/substitutions) is legitimately included by every
	// app group, each stamping its own `namespace:` — so the SAME dir under a
	// DIFFERENT inherited namespace produces a DIFFERENT ConfigMap id and must
	// be walked again. Keying by dir alone would attribute the CM to whichever
	// group walked the component first.
	key := dir + "\x00" + parentNS
	if _, seen := visited[key]; seen {
		return // cycle / repeated-under-same-namespace guard
	}
	visited[key] = struct{}{}

	d, ok := b.directives(dir)
	if !ok {
		return
	}
	baseNS := cmp.Or(parentNS, d.Namespace)

	for _, r := range d.Resources {
		resolved, ok := resolveResourcePath(dir, r)
		if !ok {
			continue
		}
		resolved = filepath.ToSlash(resolved)
		info, err := os.Stat(filepath.Join(b.repoRoot, resolved))
		if err != nil {
			continue
		}
		if info.IsDir() {
			b.walkBase(resolved, baseNS, rootNS, ks, visited)
			continue
		}
		// File resource — re-impose the stricter, escape-rejecting policy
		// used for paths that get opened (resolveResourcePath permits
		// escapes for the dir-descent case only).
		if _, ok := resolveDataPath(dir, r); !ok {
			continue
		}
		b.recordProduced(resolved, baseNS, rootNS, ks)
	}

	for _, c := range d.Components {
		resolved, ok := resolveComponentPath(dir, c)
		if !ok {
			continue
		}
		// A component carries no namespace of its own that wins over the
		// including base — baseNS flows in as the parent and stays locked.
		b.walkBase(filepath.ToSlash(resolved), baseNS, rootNS, ks, visited)
	}
}

// recordProduced parses one file `resources:` entry and records what it
// produces: every ConfigMap into the self-produce index, every ExternalSecret /
// SealedSecret into the producer index (+ a placeholder target Secret), and
// every SOPS-wiped Secret into the store (see materializeSecret). It rides
// decodeFileObjects with keepRaw so ExternalSecret / SealedSecret — which parse
// as RawObject and parseFile drops — are visible, while inheriting the shared
// parse-error / envsubst filtering, so the recorded ConfigMap set stays
// identical to the prior parseFile-based recording.
func (b *selfProduceBuilder) recordProduced(relFile, baseNS, rootNS string, ks manifest.NamedResource) {
	_ = decodeFileObjects(filepath.Join(b.repoRoot, relFile),
		manifest.ParseDocOptions{WipeSecrets: true}, true,
		func(obj manifest.BaseManifest) {
			switch o := obj.(type) {
			case *manifest.ConfigMap:
				b.recordConfigMap(o, baseNS, rootNS, ks)
			case *manifest.Secret:
				b.materializeSecret(o, baseNS, rootNS)
			case *manifest.Kustomization:
				b.recordEmittedKS(relFile, ks)
			case *manifest.RawObject:
				b.recordProducer(o, baseNS, rootNS)
			}
		})
}

// materializeSecret pre-loads an in-repo SOPS-wiped Secret into the store under
// its rendered namespace, so a Kustomization that substituteFroms a secret its
// OWN render produces resolves it to placeholders at Prepare time. The
// cluster-config self-produce pattern hits this: a substitutions component holds
// cluster-secrets, and the root Kustomization substituteFroms it — but it isn't
// in the store until that very render runs, so its Prepare-time lookup would
// otherwise see it absent and flag it unreadable / render its ${VAR}s empty.
// Like a SOPS secret's keys are knowable though its values aren't (and like a
// producer's declared keys, see recordProducer), the placeholder copy lets the
// vars resolve. Scoped to wipe-mode placeholder secrets — a cleartext Secret is
// left alone — and never clobbers a Secret already in the store.
func (b *selfProduceBuilder) materializeSecret(s *manifest.Secret, baseNS, rootNS string) {
	ns := cmp.Or(baseNS, s.Namespace, rootNS)
	if !b.wipeSecrets || b.store == nil || ns == "" {
		return
	}
	if !manifest.ContainsValuePlaceholder(s.StringData) && !manifest.ContainsValuePlaceholder(s.Data) {
		return
	}
	s.Namespace = ns
	if b.store.GetObject(s.Named()) == nil {
		b.store.AddObject(s)
	}
}

// recordConfigMap attributes cm to ks's self-produce set under its effective
// namespace: the active transformer (baseNS) wins, then the resource's own,
// then the consumer-side rootNS fallback (so a namespace-less CM still matches
// a same-namespace substituteFrom lookup).
func (b *selfProduceBuilder) recordConfigMap(cm *manifest.ConfigMap, baseNS, rootNS string, ks manifest.NamedResource) {
	ns := cmp.Or(baseNS, cm.Namespace, rootNS)
	if ns == "" {
		return
	}
	id := manifest.NamedResource{Kind: manifest.KindConfigMap, Namespace: ns, Name: cm.Name}
	b.idx.byID[id] = appendUniqueProducer(b.idx.byID[id], ks)
}

// recordEmittedKS notes that ks's render subtree reaches a Flux Kustomization
// defined at relFile — i.e. ks emits that cross-tree base. Accumulated per file;
// resolved to a single-parent gate after the walk (see EmissionParentByFile).
func (b *selfProduceBuilder) recordEmittedKS(relFile string, ks manifest.NamedResource) {
	b.emittedFiles[relFile] = appendUniqueProducer(b.emittedFiles[relFile], ks)
}

// recordProducer records the target(s) a producer generates — the Secret an
// ExternalSecret / SealedSecret materializes, or the Secret + ConfigMap an
// ObjectBucketClaim's provisioner creates — each re-keyed under the producer's
// effective namespace so it matches a consumer's same-namespace lookup.
// Non-producer kinds and a nil index are no-ops.
func (b *selfProduceBuilder) recordProducer(raw *manifest.RawObject, baseNS, rootNS string) {
	for _, target := range manifest.ProducerTargets(raw) {
		ns := cmp.Or(baseNS, target.Namespace, rootNS)
		if ns == "" {
			continue
		}
		target.Namespace = ns
		b.producers.Record(target.NamedResource, raw.Named())
		if len(target.DeclaredKeys) > 0 && target.Kind == manifest.KindSecret {
			b.synthesizePlaceholderSecret(target.NamedResource, target.DeclaredKeys)
		}
	}
}

// synthesizePlaceholderSecret materializes a stand-in Secret for a producer
// target whose output keys are statically declared but whose values flate can't
// read offline — so its ${VAR}s (postBuild substituteFrom) and valuesFrom keys
// resolve to ..PLACEHOLDER_<key>.. instead of the empty string, the same shape
// flate gives a SOPS-encrypted Secret. It never clobbers a real or SOPS-wiped
// Secret already loaded under the same id (a producer materializing a secret
// that ALSO ships in-repo is the in-repo copy's call); the GetObject guard plus
// AddObject's identical-value dedup keep the repeated walk idempotent.
func (b *selfProduceBuilder) synthesizePlaceholderSecret(target manifest.NamedResource, keys []string) {
	if !b.wipeSecrets || b.store == nil || b.store.GetObject(target) != nil {
		return
	}
	stringData := make(map[string]any, len(keys))
	for _, k := range keys {
		stringData[k] = fmt.Sprintf(manifest.ValuePlaceholderTemplate, k)
	}
	b.store.AddObject(&manifest.Secret{Name: target.Name, Namespace: target.Namespace, StringData: stringData})
}

func appendUniqueProducer(dst []manifest.NamedResource, v manifest.NamedResource) []manifest.NamedResource {
	if slices.Contains(dst, v) {
		return dst
	}
	return append(dst, v)
}
