package kustomize

import (
	"context"
	"errors"
	"strings"
	"testing"

	"sigs.k8s.io/yaml"

	"github.com/home-operations/flate/internal/testutil"
)

// TestRenderFlux_RespectsCanceledContext asserts the renderer bails
// fast when ctx is already done. The fluxcd/pkg/kustomize Generator
// and SecureBuild don't take ctx themselves, so flate checks at
// coarse boundaries — this guards that those checks fire.
func TestRenderFlux_RespectsCanceledContext(t *testing.T) {
	cache, err := NewStagingCache(t.TempDir(), 0)
	if err != nil {
		t.Fatalf("NewStagingCache: %v", err)
	}
	t.Cleanup(func() { _ = cache.Close() })

	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	_, err = RenderFlux(ctx, cache, t.TempDir(), "", ".", map[string]any{
		"apiVersion": "kustomize.toolkit.fluxcd.io/v1",
		"kind":       "Kustomization",
		"metadata":   map[string]any{"name": "k", "namespace": "ns"},
		"spec":       map[string]any{"path": "./"},
	})
	if !errors.Is(err, context.Canceled) {
		t.Errorf("expected context.Canceled, got %v", err)
	}
}

func TestSubstitute(t *testing.T) {
	in := []byte(`hello ${NAME}, version=${VERSION:=v1}, ${OPT:-x}`)
	out, err := Substitute(in, map[string]string{"NAME": "world"})
	if err != nil {
		t.Fatalf("Substitute: %v", err)
	}
	want := "hello world, version=v1, x"
	if string(out) != want {
		t.Errorf("Substitute: got %q want %q", out, want)
	}
}

// TestSubstitute_MissingVarExpandsToEmpty pins the non-strict default
// — kustomize-controller's `StrictPostBuildSubstitutions` feature gate
// is off by default, so an undefined ${VAR} in the rendered docs
// expands to the empty string rather than erroring. flate matches
// real Flux on this so repos that rely on cluster-side variables not
// visible in the on-disk YAML (e.g. ConfigMaps generated by other
// reconcile passes) still render the rest of their manifests cleanly.
func TestSubstitute_MissingVarExpandsToEmpty(t *testing.T) {
	out, err := Substitute([]byte("value=${MISSING}"), nil)
	if err != nil {
		t.Fatalf("Substitute: %v", err)
	}
	if string(out) != "value=" {
		t.Errorf("Substitute: got %q want \"value=\"", out)
	}
}

// TestSubstitute_DollarEscape — Flux's envsubst treats $${VAR} as a
// literal $ followed by ${VAR}, leaving the inner ${VAR} unsubstituted
// so a downstream shell / runtime envsubst can expand it. The previous
// regex-based engine missed this and tried to substitute anyway,
// which broke common patterns in home-ops repos (e.g. ${RUNNER_TOKEN}
// in a container's command).
func TestSubstitute_DollarEscape(t *testing.T) {
	cases := map[string]string{ //nolint:gosec // "TOKEN" / "DOMAIN" in literal templates are placeholder identifiers, not credentials
		`--token "$${RUNNER_TOKEN}"`:         `--token "${RUNNER_TOKEN}"`,
		`url: https://$${DOMAIN}/path`:       `url: https://${DOMAIN}/path`,
		`mixed $${ESCAPED} and ${UNESCAPED}`: `mixed ${ESCAPED} and HERE`,
	}
	for in, want := range cases {
		out, err := Substitute([]byte(in), map[string]string{"UNESCAPED": "HERE"})
		if err != nil {
			t.Errorf("Substitute(%q): %v", in, err)
			continue
		}
		if string(out) != want {
			t.Errorf("Substitute(%q) = %q, want %q", in, out, want)
		}
	}
}

// TestSubstitute_BashArrayBailsCleanly — Flux's envsubst parser bails
// when ${...} contains characters that aren't valid in POSIX parameter
// expansion (e.g. bash array brackets). flate now surfaces the same
// error envsubst raises rather than greedily matching the inner
// identifier and reporting it as a missing variable.
func TestSubstitute_BashArrayBailsCleanly(t *testing.T) {
	in := []byte(`for x in "${ARR[@]}"; do echo "$x"; done`)
	_, err := Substitute(in, map[string]string{"ARR": "ignored"})
	if err == nil {
		t.Fatalf("expected envsubst parse error for bash array")
	}
	if !strings.Contains(err.Error(), "missing closing brace") {
		t.Errorf("unexpected error: %v", err)
	}
}

// TestSubstitute_BashSubstringRemoval — Flux's envsubst recognizes
// POSIX-style ${VAR%%pattern} (strip-longest-suffix). The previous
// regex over-matched; envsubst handles this correctly when the var
// is defined.
func TestSubstitute_BashSubstringRemoval(t *testing.T) {
	in := []byte(`host=${ADDR%%:*}`)
	out, err := Substitute(in, map[string]string{"ADDR": "example.com:8080"})
	if err != nil {
		t.Fatalf("Substitute: %v", err)
	}
	if string(out) != "host=example.com" {
		t.Errorf("Substitute = %q, want %q", out, "host=example.com")
	}
}

// TestRenderFlux_HonorsCommonMetadata asserts that
// spec.commonMetadata.labels and spec.commonMetadata.annotations are
// merged into every rendered resource — kustomize-controller does this
// via ssautil.SetCommonMetadata after build, fluxcd/pkg/kustomize.Generator
// itself does not.
func TestRenderFlux_HonorsCommonMetadata(t *testing.T) {
	src := t.TempDir()
	testutil.WriteFile(t, src, "cm.yaml",
		"apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: c\n  namespace: ns\n  labels:\n    app: x\n  annotations:\n    note: y\ndata:\n  k: v\n")
	testutil.WriteFile(t, src, "kustomization.yaml", "resources:\n- cm.yaml\n")

	cache, err := NewStagingCache(t.TempDir(), 0)
	if err != nil {
		t.Fatalf("NewStagingCache: %v", err)
	}
	t.Cleanup(func() { _ = cache.Close() })

	out, err := RenderFlux(context.Background(), cache, src, "", ".", map[string]any{
		"apiVersion": "kustomize.toolkit.fluxcd.io/v1",
		"kind":       "Kustomization",
		"metadata":   map[string]any{"name": "k", "namespace": "ns"},
		"spec": map[string]any{
			"path": "./",
			"commonMetadata": map[string]any{
				"labels":      map[string]any{"team": "flate", "app": "override"},
				"annotations": map[string]any{"managed-by": "flate"},
			},
		},
	})
	if err != nil {
		t.Fatalf("RenderFlux: %v", err)
	}

	var got map[string]any
	if err := yaml.Unmarshal(out, &got); err != nil {
		t.Fatalf("unmarshal output: %v\n%s", err, out)
	}
	md, _ := got["metadata"].(map[string]any)
	labels, _ := md["labels"].(map[string]any)
	annotations, _ := md["annotations"].(map[string]any)
	if labels["team"] != "flate" {
		t.Errorf("commonMetadata.labels not merged: %v", labels)
	}
	if labels["app"] != "override" {
		t.Errorf("commonMetadata.labels did not override existing: %v", labels)
	}
	if annotations["managed-by"] != "flate" {
		t.Errorf("commonMetadata.annotations not merged: %v", annotations)
	}
	if annotations["note"] != "y" {
		t.Errorf("existing annotations dropped: %v", annotations)
	}
	// applyOwnerLabels: every rendered resource should carry the parent
	// Kustomization's name + namespace under kustomize.toolkit.fluxcd.io/*.
	if labels["kustomize.toolkit.fluxcd.io/name"] != "k" {
		t.Errorf("owner name label missing: %v", labels)
	}
	if labels["kustomize.toolkit.fluxcd.io/namespace"] != "ns" {
		t.Errorf("owner namespace label missing: %v", labels)
	}
}

// TestRenderFlux_CommonMetadataOverridesOwnerLabels pins the
// kustomize-controller-matching precedence rule: when commonMetadata
// supplies a key that collides with the owner-label keys
// (kustomize.toolkit.fluxcd.io/{name,namespace}), commonMetadata wins.
// Upstream applies SetOwnerLabels at reconcile setup, then
// SetCommonMetadata at apply time — so a future revert of the
// applyOwnerLabels/applyCommonMetadata ordering in flux.go would be
// caught here.
func TestRenderFlux_CommonMetadataOverridesOwnerLabels(t *testing.T) {
	src := t.TempDir()
	testutil.WriteFile(t, src, "cm.yaml",
		"apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: c\n  namespace: ns\ndata:\n  k: v\n")
	testutil.WriteFile(t, src, "kustomization.yaml", "resources:\n- cm.yaml\n")
	cache, err := NewStagingCache(t.TempDir(), 0)
	if err != nil {
		t.Fatalf("NewStagingCache: %v", err)
	}
	t.Cleanup(func() { _ = cache.Close() })

	out, err := RenderFlux(context.Background(), cache, src, "", ".", map[string]any{
		"apiVersion": "kustomize.toolkit.fluxcd.io/v1",
		"kind":       "Kustomization",
		"metadata":   map[string]any{"name": "owner-name", "namespace": "owner-ns"},
		"spec": map[string]any{
			"path": "./",
			"commonMetadata": map[string]any{
				"labels": map[string]any{
					"kustomize.toolkit.fluxcd.io/name":      "user-override",
					"kustomize.toolkit.fluxcd.io/namespace": "user-ns-override",
				},
			},
		},
	})
	if err != nil {
		t.Fatalf("RenderFlux: %v", err)
	}

	var got map[string]any
	if err := yaml.Unmarshal(out, &got); err != nil {
		t.Fatalf("unmarshal output: %v\n%s", err, out)
	}
	md, _ := got["metadata"].(map[string]any)
	labels, _ := md["labels"].(map[string]any)
	if labels["kustomize.toolkit.fluxcd.io/name"] != "user-override" {
		t.Errorf("commonMetadata should win on owner-name collision; got %v",
			labels["kustomize.toolkit.fluxcd.io/name"])
	}
	if labels["kustomize.toolkit.fluxcd.io/namespace"] != "user-ns-override" {
		t.Errorf("commonMetadata should win on owner-namespace collision; got %v",
			labels["kustomize.toolkit.fluxcd.io/namespace"])
	}
}

// TestRenderFlux_InjectsOwnerLabels guards that
// kustomize.toolkit.fluxcd.io/{name,namespace} land on rendered
// resources even without spec.commonMetadata.
func TestRenderFlux_InjectsOwnerLabels(t *testing.T) {
	src := t.TempDir()
	testutil.WriteFile(t, src, "cm.yaml",
		"apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: c\n  namespace: ns\ndata:\n  k: v\n")
	testutil.WriteFile(t, src, "kustomization.yaml", "resources:\n- cm.yaml\n")
	cache, err := NewStagingCache(t.TempDir(), 0)
	if err != nil {
		t.Fatalf("NewStagingCache: %v", err)
	}
	t.Cleanup(func() { _ = cache.Close() })

	out, err := RenderFlux(context.Background(), cache, src, "", ".", map[string]any{
		"apiVersion": "kustomize.toolkit.fluxcd.io/v1",
		"kind":       "Kustomization",
		"metadata":   map[string]any{"name": "infra", "namespace": "flux-system"},
		"spec":       map[string]any{"path": "./"},
	})
	if err != nil {
		t.Fatalf("RenderFlux: %v", err)
	}
	var got map[string]any
	if err := yaml.Unmarshal(out, &got); err != nil {
		t.Fatalf("unmarshal output: %v\n%s", err, out)
	}
	md, _ := got["metadata"].(map[string]any)
	labels, _ := md["labels"].(map[string]any)
	if labels["kustomize.toolkit.fluxcd.io/name"] != "infra" {
		t.Errorf("owner name label = %v, want infra", labels["kustomize.toolkit.fluxcd.io/name"])
	}
	if labels["kustomize.toolkit.fluxcd.io/namespace"] != "flux-system" {
		t.Errorf("owner namespace label = %v, want flux-system", labels["kustomize.toolkit.fluxcd.io/namespace"])
	}
}
