// Package diff produces structured diffs between two sets of rendered
// Kubernetes manifests. The diff body is generated by [dyff] in its
// `--output github` mode — path-keyed (`@@ <path> @@`) with standard
// `+` / `-` value lines and `!` change-type markers, which GitHub's
// diff lexer renders natively as a colored diff block when wrapped
// in a ```diff fence. The substantive payoff over a textual unified
// diff is K8s-aware list matching: containers, env vars, and other
// named list entries are paired by their identifier (`.name`), so
// reordering a list produces an `⇆ order changed` marker instead of
// a wall of phantom value-line churn.
//
// Options.StripAttrs is applied to a deep-copied tree before the
// comparison runs — used to drop chart-bump noise (`helm.sh/chart`,
// `checksum/config`, …) that rotates on every Helm upgrade but
// carries no review-relevant signal.
//
// Three output flavors are supported:
//
//   - Diff — concatenated dyff bodies, one per resource. Every body
//     is prefixed with a single `#`-style header line identifying
//     the parent KS/HR and the child resource (the default).
//   - YAML — structured YAML where each entry is a resource and its
//     dyff body.
//   - JSON — same shape as YAML, marshaled as JSON.
//
// [dyff]: https://github.com/homeport/dyff
package diff
